'''
Adaptation of run_gsn.py to run experiment inpainting MNIST dataset with missing
pixels. Requires the model and configuration files generated by running run_gsn.py
according to original instructions.

Usage:
python run_gsn_missing_data.py --test_model 1 --missing_data_dir <MISSING_DATA_DIR> --save_path <OUTPUT_DIR>

Notes:
- GSN Model must be trained beforehand, following original instructions 
(experiment 1 in https://github.com/yaoli/GSN). The needed 
files are config and params_epoch_XXXX.pkl where XXXX is the final epoch)
- <MISSING_DATA_DIR> should contain index_mask.txt file containing mask info corresponding to MNIST validation set 
samples. Experiment currently set to inpaint full MNIST validation set.

'''
import argparse
import model_missing_data

def main():
    parser = argparse.ArgumentParser()
    # Add options here

    parser.add_argument('--K', type=int, default=2) # nubmer of hidden layers
    parser.add_argument('--N', type=int, default=4) # number of walkbacks
    parser.add_argument('--n_epoch', type=int, default=1000)
    parser.add_argument('--batch_size', type=int, default=100)
    parser.add_argument('--hidden_add_noise_sigma', type=float, default=2)
    parser.add_argument('--input_salt_and_pepper', type=float, default=0.4)
    parser.add_argument('--learning_rate', type=float, default=0.25)
    parser.add_argument('--momentum', type=float, default=0.5)
    parser.add_argument('--annealing', type=float, default=0.995)
    parser.add_argument('--hidden_size', type=float, default=1500)
    parser.add_argument('--act', type=str, default='tanh')
    parser.add_argument('--dataset', type=str, default='MNIST')
    parser.add_argument('--data_path', type=str, default='.')
    parser.add_argument('--missing_data_dir', type=str, default='.')
    parser.add_argument('--save_path', type=str, default='.')
   
    # argparse does not deal with bool 
    parser.add_argument('--vis_init', type=int, default=0)
    parser.add_argument('--noiseless_h1', type=int, default=1)
    parser.add_argument('--input_sampling', type=int, default=1)
    parser.add_argument('--test_model', type=int, default=0)
    
    args = parser.parse_args()
   
    print args.test_model 
    
    model_missing_data.experiment(args, None)
    
if __name__ == '__main__':
    main()
